<a href="https://colab.research.google.com/github/d22cs051/Leaning-DL/blob/main/pytorch_exercises/Copy_of_00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
T1 = torch.randn((7,7))
T1

tensor([[ 0.1984,  0.7821,  1.0391, -0.7245, -0.8489, -1.2169, -0.0810],
        [ 1.3615, -2.0615,  0.6741, -1.3233, -1.3598, -0.8667, -0.5640],
        [-2.0565, -0.3567,  0.9571, -0.6619, -0.8285, -0.6057, -0.1354],
        [ 0.7471,  0.6118,  1.8678, -0.2616, -0.2501,  0.5011,  0.2600],
        [-1.6370,  0.1577,  0.3957, -1.3677, -2.9662, -1.7178, -0.5824],
        [-0.6153,  1.5496,  0.5989, -0.6377, -2.2858, -0.3677, -0.3866],
        [-1.0370,  0.5920, -0.7557,  0.3917,  0.7470,  1.3798,  1.2877]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
T2 = torch.randn((1,7))
# T2
# Perform matrix multiplication 
matmul_op = torch.matmul(T1,T2.T)
matmul_op

tensor([[-0.6652],
        [-0.1072],
        [-2.5226],
        [-2.3828],
        [-1.2671],
        [-1.4955],
        [ 0.0619]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
T3 = torch.randn((2,2))
T4 = torch.randn((2,2))
# Matrix multiply tensors
# print(T3)
# print(T4)
MM = torch.matmul(T3,T4)
print(MM)

tensor([[-1.7896, -2.4011],
        [ 2.5922,  3.5236]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Create two random tensors on GPU
T_gpu1 = torch.randn((2,3),device=device)
T_gpu2 = torch.randn((2,3),device=device)
print(T_gpu1)
print(T_gpu2)

tensor([[-1.6165,  0.5685, -0.5102],
        [-0.9113, -1.1555, -0.2262]], device='cuda:0')
tensor([[ 0.6331,  1.6358, -0.3459],
        [ 1.0196, -0.4122,  1.4279]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
MM_gpu = T_gpu1 @ T_gpu2.T
print(MM_gpu)

tensor([[ 0.0830, -2.6109],
        [-2.3890, -0.7758]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(torch.max(MM_gpu))
# Find min
print(torch.min(MM_gpu))

tensor(0.0830, device='cuda:0')
tensor(-2.6109, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(torch.argmax(MM_gpu))

# Find arg min
print(torch.argmin(MM_gpu))

tensor(0, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)
# Create random tensor
T5 = torch.randn((1,1,1,10))
print(T5,T5.shape)
# Remove single dimensions
T5 = T5.flatten()

# Print out tensors and their shapes
print(T5,T5.shape)

tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]]) torch.Size([1, 1, 1, 10])
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822]) torch.Size([10])
